# application.yml
server:
  port: 8082
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

logging:
  level:
    org:
      springframework:
        security: DEBUG

app:
  jwtExpirationInMs: 600
